baseURL = "https://hugopress.razonyang.com/"
title = "HugoPress"

[[module.imports]]
path = "github.com/hugomods/base"

[[module.imports]]
path = "github.com/hugomods/hugopress"

[params]

[params.hugopress]
[params.hugopress.modules.hello]
[params.hugopress.modules.hello.attributes.document]
[params.hugopress.modules.hello.attributes.body]
[params.hugopress.modules.hello.hooks.head-end]
[params.hugopress.modules.hello.hooks.body-begin]
weight = 3

[params.hugopress.modules.foo]
[params.hugopress.modules.foo.attributes.document]
cacheable = true
[params.hugopress.modules.foo.attributes.body]
cacheable = true
[params.hugopress.modules.foo.hooks.head-end]
cacheable = true
[params.hugopress.modules.foo.hooks.body-begin]
cacheable = true
#weight = 1

[params.hugopress.modules.bar]
[params.hugopress.modules.bar.attributes.body]
disable = true
[params.hugopress.modules.bar.hooks.body-begin]
disable = true

[params.hugopress.modules.disabled]
disable = true
[params.hugopress.modules.disabled.attributes.document]
[params.hugopress.modules.disabled.attributes.body]
[params.hugopress.modules.disabled.hooks.head-end]
[params.hugopress.modules.disabled.hooks.body-begin]
#weight = 1
